# Generated by Django 2.0.6 on 2018-06-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=75)),
                ('apellidos', models.CharField(max_length=75)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=8)),
                ('correo', models.EmailField(max_length=125)),
                ('password', models.CharField(max_length=75)),
                ('genero', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('cui', models.CharField(max_length=13)),
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('autorizacion', models.BooleanField()),
            ],
        ),
    ]
