# Generated by Django 2.0.6 on 2018-06-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='administrador',
            new_name='administradores',
        ),
    ]
