# Generated by Django 2.0.6 on 2018-06-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auto_20180615_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=75)),
                ('apellidos', models.CharField(max_length=75)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=8)),
                ('correo', models.EmailField(max_length=125)),
                ('password', models.CharField(max_length=75)),
                ('genero', models.CharField(max_length=10)),
                ('fecha_nac', models.DateField()),
                ('cui', models.CharField(max_length=13)),
                ('autorizacion', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=75)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=75)),
            ],
        ),
        migrations.DeleteModel(
            name='administradores',
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Pais'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Municipio'),
        ),
    ]
