# Generated by Django 2.0.6 on 2018-06-29 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_auto_20180629_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='apellidos',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='correo',
            field=models.EmailField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='cui',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='fecha_nac',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='genero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Municipio'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='password',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='telefono',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
