# Generated by Django 2.0.6 on 2018-06-30 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_remove_administrador_autorizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='apellidos',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='correo',
            field=models.EmailField(max_length=125),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='cui',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='direccion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='fecha_nac',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='genero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Municipio'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='password',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='telefono',
            field=models.CharField(max_length=8),
        ),
    ]
