# Generated by Django 2.0.6 on 2018-07-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_auto_20180629_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='municipio',
        ),
    ]
