# Generated by Django 2.0.6 on 2018-07-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_remove_administrador_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='password',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
