# Generated by Django 2.0.6 on 2018-07-02 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0011_auto_20180701_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=75)),
                ('apellidos', models.CharField(max_length=75)),
                ('genero', models.CharField(max_length=10)),
                ('fecha_ingreso', models.CharField(max_length=10)),
                ('fecha_nac', models.CharField(max_length=10)),
                ('fecha_fall', models.CharField(max_length=10)),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=125)),
                ('ubicacion', models.CharField(max_length=150)),
                ('existencia', models.IntegerField()),
                ('fecha_ingreso', models.CharField(max_length=10)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=75)),
                ('fecha_ingreso', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Tema'),
        ),
    ]
