# Generated by Django 2.0.6 on 2018-07-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0013_auto_20180706_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='id',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='correo',
            field=models.EmailField(max_length=125, primary_key=True, serialize=False),
        ),
    ]
