# Generated by Django 2.0.6 on 2018-07-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0014_auto_20180707_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tema',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
    ]
