# Generated by Django 2.0.7 on 2018-07-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0017_biblioteca'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='biblioteca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Biblioteca'),
        ),
    ]
