# Generated by Django 2.0.7 on 2018-07-19 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0019_auto_20180717_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='latitud',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='longitud',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
