# Generated by Django 2.0.7 on 2018-07-24 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0020_auto_20180719_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrador.Municipio'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrador.Pais'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrador.Pais'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrador.Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='biblioteca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='administrador.Biblioteca'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrador.Tema'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrador.Departamento'),
        ),
    ]
