# Generated by Django 2.0.7 on 2018-07-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0021_auto_20180724_0911'),
        ('administrador', '0019_auto_20180718_1424'),
    ]

    operations = [
    ]
