# Generated by Django 2.0.7 on 2018-07-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0022_merge_20180726_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='latitud',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='longitud',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
