# Generated by Django 2.0.7 on 2018-07-11 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0016_auto_20180708_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolaridad', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombres', models.CharField(max_length=75)),
                ('apellidos', models.CharField(max_length=75)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=8)),
                ('correo', models.EmailField(max_length=125, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=75)),
                ('genero', models.CharField(max_length=10)),
                ('fecha_nac', models.CharField(max_length=10)),
                ('cui', models.CharField(max_length=13)),
                ('zona', models.IntegerField(max_length=2)),
                ('institucion', models.CharField(max_length=75)),
                ('foto', models.TextField()),
                ('escolaridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Escolaridad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Municipio')),
            ],
        ),
    ]
