# Generated by Django 2.0.7 on 2018-07-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20180712_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamos',
            old_name='Usuario',
            new_name='usuario',
        ),
    ]
